name: Remove old artifacts

on:
  schedule:
    # Every 15mins
    - cron: '*/15 * * * *'

jobs:
  remove-old-artifacts:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '120 seconds' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5